### ISSUE TITLE
Filtering on content with graphQL

### ISSUE THREAD

**Issue by ttasovac** [raffazizzi/gatsby-theme-ceteicean#2]
Ok, so we can use graphQL to get all of our static TEI content like this:

```js
const result = await graphql(`
  query {
    allCetei {
      nodes {
        prefixed
        elements
        parent {
          ... on File {
            name
          }
        }
      }
    }
  }
`);
```

but if we were building a multilingual website and we wanted to get only to the content in a particular language, based on, say `/TEI/@xml:lang`, how would be go about it?

Many thanks in advance!

**Comment by raffazizzi** [comment]
I usually handle bilingual content at component level and show content in a certain language based on React Context or other state management.

Here is [an example](https://gitlab.com/scholarly-editing/se-microedition-mbs/-/blob/main/src/gatsby-theme-ceteicean/components/Entity.tsx?ref_type=heads#L78) for handling `<person><note xml:lang"fr"></note><note xml:lang="en"></note></person>` based on a value set with React Context.

This approach provides data in both languages to the client and lets React handle what to push to the DOM. 

However, if you're interested in passing less data to the client, or in generating different pages based on language (or other factors), I would consider transforming content before it gets to the client.

You can do this in `gatsby-node.js`, like I discussed in issue #1, or—perhaps better—pass a transformation script (in node or even XSLT via saxonjs) to the underlying gatsby-transformer-ceteicean. See the example [at the end of "How to Use"](https://gitlab.com/scholarly-editing/se-microedition-mbs/-/blob/main/src/gatsby-theme-ceteicean/components/Entity.tsx?ref_type=heads#L78) in the README. A few more details are in the README for [gatsby-transformer-ceteicean](https://github.com/raffazizzi/gatsby-transformer-ceteicean/).

**Comment by raffazizzi** [comment]
But essentially, it's not possible to query TEI content using GraphQL: it only provides a string version of the TEI (original), the CETEIcean-ready TEI (prefixed), and a list of elements. Any server-side operations on the TEI require a DOM, or string operations.

**Comment by ttasovac** [comment]
I will have to think a little more about this, but your tips should get me going... I won't be able to work on it today, though, so I may get back to you at some point later if I still have some questions...

Thanks a lot, Raff! I really appreciate your help.

**Comment by raffazizzi** [comment]
If you have a use case for exposing more of the TEI _structure_ to the graphql layer let me know... at the end of the day it could ingest a JSON structure of some kind... Leaving this issue open as we explore this possibility.

**Comment by ttasovac** [comment]
Hey Raff,

I've discovered something weird: `gatsby-node.js` in the project root folder doesn't completely overwrite the theme's `gatsby-node.js` which can lead to build errors in some cases.

Let me explain.

My i18 setup is such that language-specific pages are prefixed: `/en/test` and `/sr/test` should serve content in the appropriate language.

My corresponding static files are: `test_en.xml` and `test_sr.xml`. I do _not_ want to have urls like `/en/test_en` and `/sr/test_sr` because they offend my esthetic sensibilities :) 

So, what I did in my root `gatsby-node.js` is reconstruct the results of the graphql query (which is done on TEI files with the language extension in the title) to get rid of the extension in the `name`, so that I can only create a single page `/test` and pass the prefixed content in _both_ languages to it like this:

```js
createPage({
  path: name,
  component,
  context: {
    sr: {
      name,
      title: node.title_sr,
      description: node.description_sr,
      prefixed: node.prefixed_sr,
      elements: node.elements
    },
    en: {
      name,
      title: node.title_en,
      description: node.description_en,
      prefixed: node.prefixed_en,
      elements: node.elements
    }
  }
})
```

which, then, makes it trivial to render:

```js
<Ceteicean
  pageContext={lang === 'en' pageContext.en : pageContext.sr} routes={routes}
/>
```

Everything works as expected with `gatsby develop`, but on `gatsby build`, the build fails with

`Building static HTML failed for path "/sr/test_en/"`

I was really surprised at first -- because my `gatsby-node.js` does not call for the page `test_en` to be created at all.

It turns out that gatsby's theme set up is such that only `src` files are "shadowed", i.e. can be extended, overridden etc. The theme's `gatsby-node.js`, however, continues to create pages. And because I _am_ overriding the `Ceteicean` component, the pages created by the theme's `gatsby-node.js` (`test_en` etc.) end up failing because they don't have the right `pageContext`. This is 100% the case, because when I comment out the theme's `gatsby-node.js` in my local environment, the build will complete without a glitch.

This is totally crazy! So I guess I have several options now:

1) stop using `gatsby-theme-ceteicean` as an external theme and reconstruct it locally with my version of `gatsby-node.js` -- I'd prefer not to do this
2) fork `gatsby-theme-ceteicean`, rename it and publish it with my version of `gatsby-node.js``; or
3) explore XSLT transformations.

To be honest, I'm not sure that XSLT could help in this particular setup, where I want to have separate TEI files for one url path, or am I missing something?

**Comment by raffazizzi** [comment]
Hi @ttasovac , you're correct that the theme's `gastby-node.js` cannot be shadowed (my understanding is that this is true for all Gatsby themes). The default behavior for the theme is to generate a page for every XML file that is loaded into GraphQL from the location set through `gatsby-source-filesystem`. 

This is to keep things simple out-of-the box: just add the plugin, tell it where to look, and you'll have TEI rendered at pages with the same names as the TEI files. Add CSS and you're done.

I wouldn't want to lose the simplicity of this, but your use case makes perfect sense. Incidentally, I haven't come across it because usually I create new additional pages by combining nodes (e.g. for a synoptic view), but am still happy to have an endpoint for each TEI file.

Since `gatsby-node.js` can't be shadowed, I wonder if we can solve this via a plugin configuration that turns off the automatic page generation, or that excludes certain files / paths from getting automatically generated. What do you think?

I can try to work on this ASAP, but if you are willing, feel free to work on a patch and send in a PR!

**Comment by raffazizzi** [comment]
Hi @ttasovac I just released a new version that allows to turn off `createPages` for all files, or a selection of files. See the README for more info. In short, this should address your use case:

```js
{
  resolve: `gatsby-theme-ceteicean`,
  options: {
    fullShadow: true
  }
}
```

Please give it a try and let me know if this fixes it for you!

**Comment by ttasovac** [comment]
Amazing! Thanks a lot @raffazizzi —  this fixes the issue for me!
